Document how to use robotology-superbuild software with WSL2
robotology/robotology-superbuild pull request #468
Opened 2020-09-09 16:01 UTC by traversaro

Fix https://github.com/robotology/robotology-superbuild/issues/361 by documenting the use of `/etc/wsl.conf` for WSL2 that for sure it supports it, and leaving the old workaround for WSL1. 

Fix https://github.com/robotology/robotology-superbuild/issues/427 with an in-depth guide on how to configure X Servers with WSL2.

2020-09-09 16:27 UTC, pattacini requested changes
A few minor typos to fix

2020-09-09 16:27 UTC, pattacini commented on README.md
> +The Linux instance in WSL2 are running as part of a lightweight virtual machine, so effectively the IP addresso of the WSL2 instance will be different from the IP address
`address`

2020-09-09 16:27 UTC, pattacini commented on README.md
> +As all the software running on Linux distributions can run unmodified on Windows via WSL, to install the robotology-superbuild in WSL you can just install a Debian-based distribution for WSL, and the
a few things

2020-09-09 16:27 UTC, pattacini commented on README.md
> +y default, the `PATH` enviroment variable in WSL will contain the path of the host Windows system, see https://github.com/microsoft/WSL/issues/1640 and https://github.com/microsoft/WSL/issues/1493. T
By default

2020-09-10 11:43 UTC, traversaro commented
Thanks @pattacini , I fixed your comments in https://github.com/robotology/robotology-superbuild/pull/468/commits/8704086607888bd68f58ac90b35b51005adc3025 .

2020-09-10 11:47 UTC, pattacini approved these changes

2020-09-10 12:16 UTC, merged