Restore regular YARP branches
robotology/robotology-superbuild pull request #471
Opened 2020-09-11 14:21 UTC by traversaro

As https://github.com/robotology/yarp/pull/2356 has been merged.

2020-09-11 14:28 UTC, S-Dafarra requested changes

2020-09-11 14:28 UTC, S-Dafarra commented on cmake/ProjectsTagsStable.cmake
>  set_tag(YARP_TAG 0328577b5f102da2875517898d8a6439ac9374d2)
Probably this has to be removed

2020-09-11 14:39 UTC, traversaro commented on cmake/ProjectsTagsStable.cmake
>  set_tag(YARP_TAG 0328577b5f102da2875517898d8a6439ac9374d2)
Thanks, done!

2020-09-11 14:44 UTC, S-Dafarra approved these changes

2020-09-11 15:07 UTC, traversaro commented
Apparently the change in https://github.com/robotology/yarp/pull/2356 still needs to be propagated to `master`, so we need to wait for that to merge this PR, because the `Stable` branches give an error as the default branch of YARP is `master`, and the error emerges before switching to `yarp-3.4`.

2020-09-14 09:53 UTC, traversaro commented
The automatic merging of `yarp-3.4` in `master` was broken by exactly the same problem described in https://github.com/robotology/yarp/pull/2356 . Now the merge has been done manually, so the PR is ready to be merged.

2020-09-15 07:16 UTC, merged