Add documentation for ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS profile
robotology/robotology-superbuild pull request #538
Opened 2020-11-27 09:29 UTC by GiulioRomualdi

2020-11-27 09:33 UTC, traversaro commented on doc/profiles.md
> +[tbeu/matio](https://github.com/tbeu/matio/) is aslo an optional system dependency of `wb-toolbox`.
```suggestion
[tbeu/matio](https://github.com/tbeu/matio/) is also an optional system dependency of `wb-toolbox`.
```

2020-11-27 09:36 UTC, traversaro commented on doc/profiles.md
> +On windows the installation of `CppAD` is currently disabled because of https://github.com/coin-or/CppAD/pull/63 and https://github.com/coin-or/CppAD/pull/61. The user can however install CppAD with
The problem is that the cppad installed by vcpkg would not be found by `find_or_build_package` due to the use of `YCM_DISABLE_SYSTEM_PACKAGES`, so for now I just say that cppad is not supported, or say that to use the cppad's of vcpkg you need to manually set `YCM_DISABLE_SYSTEM_PACKAGES` to `OFF` .

2020-11-30 07:28 UTC, traversaro requested changes
See comment https://github.com/robotology/robotology-superbuild/pull/538/files#r531484470 . If we just enable cppad on Windows following https://github.com/robotology/robotology-superbuild/pull/544, probably we can just remove that sentence.

2020-12-01 10:16 UTC, GiulioRomualdi commented
We can also remove the sentence related to `matio` given to #539

2020-12-03 10:47 UTC, GiulioRomualdi commented
@traversaro I updated the documentation as discussed in https://github.com/robotology/robotology-superbuild/pull/538#pullrequestreview-540650374 and https://github.com/robotology/robotology-superbuild/pull/538#issuecomment-736378422

Let me know if I've to change something else

2020-12-03 10:47 UTC, traversaro approved these changes

2020-12-03 10:48 UTC, traversaro commented
Thanks @GiulioRomualdi !

2020-12-03 10:48 UTC, merged